/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Order
 */
export interface Order {
    'id'?: number;
    'petId'?: number;
    'quantity'?: number;
    'shipDate'?: string;
    'status'?: OrderStatus;
    'complete'?: boolean;
}

export const OrderStatus = {
    Placed: 'placed',
    Approved: 'approved',
    Delivered: 'delivered'
} as const;

export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];


